const crypto = require('crypto');
const logger = require('../utils/logger');

const CSRF_COOKIE_NAME = 'csrf_token';
const CSRF_HEADER_NAME = 'x-csrf-token';

const CSRF_TOKEN_BYTES = 32;

/*
 * Create the cookie/header token.

 * Format:
 *
 * randomToken.signature
 *
 * The signature prevents an attacker from simply choosing
 * an arbitrary CSRF cookie value.
 */
function createCsrfToken() {
    const token = crypto
        .randomBytes(CSRF_TOKEN_BYTES)
        .toString('hex');

    const signature = crypto
        .createHmac('sha256', getCsrfSecret())
        .update(token)
        .digest('hex');

    return `${token}.${signature}`;
}

function getCsrfSecret() {
    const secret = process.env.CSRF_SECRET;

    if (!secret || secret.length < 32) {
        throw new Error(
            'CSRF_SECRET is missing or too short. ' +
            'Add a CSRF_SECRET with at least 32 characters.'
        );
    }

    return secret;
}

/*
 * Verify that the token was signed by this backend.
 */
function verifyCsrfToken(value) {
    if (typeof value !== 'string') {
        return false;
    }

    const parts = value.split('.');

    if (parts.length !== 2) {
        return false;
    }

    const [token, signature] = parts;

    if (!token || !signature) {
        return false;
    }

    const expectedSignature = crypto
        .createHmac('sha256', getCsrfSecret())
        .update(token)
        .digest('hex');

    try {
        return crypto.timingSafeEqual(
            Buffer.from(signature, 'hex'),
            Buffer.from(expectedSignature, 'hex')
        );
    } catch {
        return false;
    }
}

/*
 * Cookie settings follow the same frontend/backend deployment model
 * as the authentication cookie.
 */
function getCsrfCookieOptions() {
    const isProd = process.env.NODE_ENV === 'production';

    const isCrossOrigin =
        !!process.env.FRONTEND_URL &&
        !process.env.FRONTEND_URL.includes('localhost');

    return {
        httpOnly: false,
        secure: isProd,
        sameSite: isProd && isCrossOrigin ? 'none' : 'lax',
        maxAge: 7 * 24 * 60 * 60 * 1000,
        path: '/',
    };
}

/*
 * Issue a CSRF token.
 *
 * Frontend calls:
 *
 * GET /api/auth/csrf
 */
function issueCsrfToken(req, res) {
    try {
        const csrfToken = createCsrfToken();

        res.cookie(
            CSRF_COOKIE_NAME,
            csrfToken,
            getCsrfCookieOptions()
        );

        return res.json({
            success: true,
            csrfToken,
        });
    } catch (err) {
        logger.error('CSRF token generation failed', {
            requestId: req.requestId,
            errorCategory: 'CSRF',
            error: err,
        });

        return res.status(500).json({
            success: false,
            error: 'Unable to initialize security token.',
        });
    }
}

/*
 * Protect state-changing browser requests.
 */
function csrfProtection(req, res, next) {
    try {
        const cookieToken = req.cookies?.[CSRF_COOKIE_NAME];
        const headerToken = req.get(CSRF_HEADER_NAME);

        if (!cookieToken || !headerToken) {
            return res.status(403).json({
                success: false,
                error: 'Invalid security token.',
                code: 'CSRF_TOKEN_REQUIRED',
            });
        }

        /*
         * Both values must match exactly.
         */
        if (cookieToken.length !== headerToken.length) {
            return res.status(403).json({
                success: false,
                error: 'Invalid security token.',
                code: 'CSRF_TOKEN_INVALID',
            });
        }

        if (
            !crypto.timingSafeEqual(
                Buffer.from(cookieToken),
                Buffer.from(headerToken)
            )
        ) {
            return res.status(403).json({
                success: false,
                error: 'Invalid security token.',
                code: 'CSRF_TOKEN_INVALID',
            });
        }

        /*
         * Verify that the token itself was generated by our server.
         */
        if (!verifyCsrfToken(cookieToken)) {
            return res.status(403).json({
                success: false,
                error: 'Invalid security token.',
                code: 'CSRF_TOKEN_INVALID',
            });
        }

        next();
    } catch (err) {
        logger.error('CSRF protection failed', {
            requestId: req.requestId,
            errorCategory: 'CSRF',
            error: err,
        });

        return res.status(403).json({
            success: false,
            error: 'Invalid security token.',
            code: 'CSRF_TOKEN_INVALID',
        });
    }
}

module.exports = {
    issueCsrfToken,
    csrfProtection,
    CSRF_COOKIE_NAME,
};